#!/bin/sh

export CONFIG=/home/alarm/config.yaml
LOG=/home/alarm/vigilantpi.log
BIN_DIR=/home/alarm

(while true; do
	echo Starting vigilantpi
    if [ -e $BIN_DIR/vigilantpi_update_ready ]; then
        echo updating binary...
        
        mv $BIN_DIR/vigilantpi $BIN_DIR/vigilantpi_bkp \
            && mv $BIN_DIR/vigilantpi_update_ready $BIN_DIR/vigilantpi \
            && echo updated... \
            || echo error updating...
    fi

	$BIN_DIR/vigilantpi
	echo vigilantpi died. restarting in 5s
	sleep 5
done) >> $LOG 2>&1
